#!/usr/bin/env node
'use strict';
// This is a proof of concept. The code below is ugly, inefficient and has no tests.

// Generate protobuf-serialized Tweet message. You probably want to pipe this output to `generate-parcel`.

const {TwitterCredentials, TweetMessage} = require('../twitter-service/messages');

require('dotenv').config();

const credentials = TwitterCredentials.create({
    accessTokenKey: process.env.TWITTER_ACCESS_TOKEN_KEY,
    accessTokenSecret: process.env.TWITTER_ACCESS_TOKEN_SECRET,
});

const message = TweetMessage.create({
    credentials: credentials,
    status: 'Hello world. 👋 I come from the Relaynet PoC (https://github.com/relaynet/poc).'
});

const messageSerialized = TweetMessage.encode(message).finish();
process.stdout.write(messageSerialized);
